replicaCount: 1

image:
  repository: ghcr.io/desponda/atc-sim
  pullPolicy: Always
  tag: "sha-9acbb37"

service:
  type: ClusterIP
  port: 80
  targetPort: 3001

ingress:
  enabled: true
  className: cloudflare-tunnel
  host: atc.dresponda.com
  annotations:
    tunnel.ingress.k8s.cloudflare.com/enable-default-route: "true"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  PORT: "3001"
  STATIC_DIR: "/app/packages/client/dist"
  NODE_ENV: "production"
